# Translations template for keystone.
# Copyright (C) 2014 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-08-04 06:06+0000\n"
"PO-Revision-Date: 2014-07-16 14:42+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: German (http://www.transifex.com/projects/p/keystone/language/"
"de/)\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: keystone/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Ursprüngliche Ausnahme wird gelöscht: %s"

#: keystone/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Unerwartete Ausnahme %d mal(e) aufgetreten... Neuversuch."

#: keystone/openstack/common/lockutils.py:119
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "Angeforderte Sperre `%s` konnte nicht freigegeben werden"

#: keystone/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "in Schleifenaufruf mit festgelegter Dauer"

#: keystone/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "in dynamischen Schleifenaufruf"

#: keystone/openstack/common/policy.py:507
#, python-format
msgid "Failed to understand rule %s"
msgstr "Regel %s konnte nicht verstanden werden"

#: keystone/openstack/common/policy.py:517
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Kein Handler für Übereinstimmungen des Typs %s"

#: keystone/openstack/common/policy.py:787
#, python-format
msgid "Failed to understand rule %r"
msgstr "Regel %r konnte nicht verstanden werden"

#: keystone/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Ausnahme bei RPC Cleanup."

#: keystone/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "Nicht behandelte Ausnahme"
